### ISSUE TITLE
What is the policy to update code on existing pull request? 

### ISSUE THREAD

**Issue by mahedee** [OpenCodeFoundation/PlanCards#12]
Say, I have created a PR. Some how code is not in up to the mark. In this case, what should I do? Do I need to create new issue? Or, just update the code, commit on the existing branch? I mean, what is the best practice?

**Comment by ratanparai** [comment]
You should update the initial pull request branch by commiting new changes as requested by the reviewer. 

One feature branch may and should have multiple commits. It is good practice to commit frequently too.

**Comment by mahedee** [comment]
@ratanparai , got it thanks.

**Comment by ratanparai** [comment]
@mahedee You are welcome bhai
