### ISSUE TITLE
Backend endpoint to create a room

### ISSUE THREAD

**Issue by ratanparai** [OpenCodeFoundation/PlanCards#4]
The room will be used for the Planning Poker game

**Comment by mahedee** [comment]
The room entity will be like as follows.
Entity Name : Room
- Id - GUID - PK
- Name - String(150) - Name of the room
- CreatedBy - GUID 
- IsActive 

@ratanparai, leave your comment here. If you have any observation

**Comment by MiliDas** [comment]
Should we consider adding a CreatedAt or CreatedDate field, @mahedee bhaiya?

**Comment by mahedee** [comment]
> Should we consider adding a CreatedAt or CreatedDate field, @mahedee bhaiya?

Yes I can. But, can you please tell me what would be the purpose of that field @MiliDas

**Comment by mahedee** [comment]
> The room will be used for the Planning Poker game 

Do you mean the entity name will be Game instead of Room? @ratanparai

**Comment by MiliDas** [comment]
I believe that since these rooms are used briefly and only once, it is necessary to clean them periodically. By incorporating a CreatedAt or CreatedDate field, we can efficiently remove older data when needed. @mahedee bhaiya

**Comment by mahedee** [comment]
> I believe that since these rooms are used briefly and only once, it is necessary to clean them periodically. By incorporating a CreatedAt or CreatedDate field, we can efficiently remove older data when needed. @mahedee bhaiya

Ok. I think, room will not be that much data to archive but yes, it can be used for sorting. Like if a user create multiple room now he want to order it by date. Then it is required. Ok. I am going to add this field. Thanks for the suggestion.
